import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProviderComponent } from "./Components/Providers";
import { AuthContextProviderComponent } from "./Components/Providers";
import { NavBar } from "./Components/NavBar";
const inter = Inter({ subsets: ["latin"] });
import { initializeApp } from "firebase/app";
import { firebaseConfig } from "./utils/firebaseConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const app = initializeApp(firebaseConfig);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProviderComponent>
          <NextUIProviderComponent>
            <NavBar />
            {children}
          </NextUIProviderComponent>
        </AuthContextProviderComponent>
      </body>
    </html>
  );
}
